### ISSUE TITLE
Error - Could not load 'plugins/MobArenaPlaceholders.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by KaptenZee** [Maroon28/MAPlaceholders#8]
Could not load 'plugins/MobArenaPlaceholders.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:155) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:453) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1800]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more

**Comment by Nesseley** [comment]
The MobArenaPlaceholder jar does not go in the /plugins folder. 

As explained here: https://github.com/mobarena/MobArenaPlaceholders it goes into
/plugins/placeholderAPI/expansions
